/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory
/mnt/bwpy/mpi/usr/lib/python-exec/python3.5/python: can't open file './high_certainty/download_sdss_images.py': [Errno 2] No such file or directory

real	0m11.761s
user	0m1.084s
sys	0m0.220s
